sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t chintan4190/react-test -f ./client/Dockerfile.dev ./client

#script:
 # - docker run chintan4190/react-test npm test -- --coverage

after_success:
  - docker build -t chintan4190/multi-client ./client
  - docker build -t chintan4190/multi-nginx ./nginx
  - docker build -t chintan4190/multi-server ./server
  - docker build -t chintan4190/multi-worker ./worker
  # Log in to the docker CLI
  - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD docker.io

  # Take those images and push them to docker hub
  - docker push chintan4190/multi-client:latest
  - docker push chintan4190/multi-nginx:latest
  - docker push chintan4190/multi-server:latest
  - docker push chintan4190/multi-worker:latest
